CREATE TABLE IF NOT EXISTS DataImport (
  Checksum CHAR(64) CHARACTER SET ascii NOT NULL PRIMARY KEY,
  SourceDatabase VARCHAR(200) NOT NULL,
  ExportedAt DATETIME(3) NOT NULL,
  CountsJson LONGTEXT NOT NULL,
  ImportedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT CK_DataImport_Counts CHECK (JSON_VALID(CountsJson))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
