CREATE TABLE IF NOT EXISTS SopImportJob (
  SopImportJobId VARCHAR(100) CHARACTER SET ascii NOT NULL PRIMARY KEY,
  Status ENUM('needs_review', 'accepted', 'published', 'failed') NOT NULL DEFAULT 'needs_review',
  OriginalFileName VARCHAR(500) NOT NULL,
  StorageKey VARCHAR(500) CHARACTER SET ascii NOT NULL,
  MediaType VARCHAR(200) NOT NULL,
  FileSize BIGINT UNSIGNED NOT NULL,
  Checksum CHAR(64) CHARACTER SET ascii NOT NULL,
  ExtractedText LONGTEXT NOT NULL,
  PreviewJson LONGTEXT NOT NULL,
  WarningsJson LONGTEXT NULL,
  TargetSopId VARCHAR(100) CHARACTER SET ascii NULL,
  TargetVersionId VARCHAR(100) CHARACTER SET ascii NULL,
  CreatedBy VARCHAR(100) CHARACTER SET ascii NOT NULL,
  CreatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UpdatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  AcceptedAt DATETIME(3) NULL,
  UNIQUE KEY UQ_SopImportJob_StorageKey (StorageKey),
  KEY IX_SopImportJob_Creator (CreatedBy, CreatedAt DESC),
  KEY IX_SopImportJob_Checksum (Checksum, CreatedBy),
  CONSTRAINT CK_SopImportJob_PreviewJson CHECK (JSON_VALID(PreviewJson)),
  CONSTRAINT CK_SopImportJob_WarningsJson CHECK (WarningsJson IS NULL OR JSON_VALID(WarningsJson)),
  CONSTRAINT FK_SopImportJob_Creator FOREIGN KEY (CreatedBy) REFERENCES Account(AccountId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vi_0900_ai_ci;
